import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'

// TODO a real fav.ico using the moxed logo [x]
// * try to animate that thing

export default function Home() {
  return (
    <div>
      <Head>
        <title>Do your really read this?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/M.ico" />
      </Head>
      <Navbar></Navbar>

      <main className={styles.main}>
        <h1>content</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="my money" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
