import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// TODO a real fav.ico using the moxed logo [x]
// * try to animate that thing

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Do your really read this?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/M.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          I am doing this with <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          And this is just the{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>What the f4ck is Next.js? &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>How the f4ck works? &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Who's using this sh4t?&rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>where the f4ck's that sh4t? &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="my money" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
